# copy right by bridgewwater
# Licenses http://www.apache.org/licenses/LICENSE-2.0
# more info see https://docs.docker.com/compose/compose-file/ or https://docker.github.io/compose/compose-file/
version: '3.8'

networks:
  default:
#volumes:
#  web-data:
services:
  template-golang-lib:
    build:
      context: ./
      dockerfile : build.dockerfile
    environment:
      - ENV_WEB_HTTPS_ENABLE=false
      - CI_DEBUG=false
    # working_dir: "/app"
    # command: ["make", "dev"]
    restart: on-failure:3 # can set always | on-failure:3 | unless-stopped